name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Chromium and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Set CHROME_BIN
      run: echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV

    - name: Run Selenium tests
      run: node tests/selenium.test.js
